# Generated by Django 5.1.15 on 2026-10-05 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
                ('center', models.CharField(blank=True, max_length=80, verbose_name='Markazi')),
                ('lat', models.FloatField(verbose_name='Kenglik')),
                ('lng', models.FloatField(verbose_name='Uzunlik')),
                ('area_km2', models.PositiveIntegerField(default=0, verbose_name='Maydoni, km²')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Aholisi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('baseline', models.JSONField(default=dict, help_text='Xavf turi kodi → 0..100 indeks', verbose_name='Bazaviy xavf indekslari')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_years', models.PositiveSmallIntegerField(choices=[(1, '1 yil'), (5, '5 yil'), (10, '10 yil'), (25, '25 yil')], default=5, verbose_name='Prognoz muddati')),
                ('hazards', models.JSONField(default=list, verbose_name='Tahlil qilingan xavflar')),
                ('notes', models.TextField(blank=True, verbose_name='Qoʻshimcha kontekst')),
                ('overall_score', models.FloatField(default=0, verbose_name='Umumiy xavf')),
                ('level', models.CharField(choices=[('low', 'Past'), ('moderate', 'Oʻrtacha'), ('high', 'Yuqori'), ('critical', 'Kritik')], default='low', max_length=12, verbose_name='Daraja')),
                ('confidence', models.PositiveSmallIntegerField(default=70, verbose_name='Ishonchlilik, %')),
                ('summary', models.TextField(blank=True, verbose_name='Xulosa')),
                ('scores', models.JSONField(default=dict, verbose_name='Xavf turlari boʻyicha ball')),
                ('timeline', models.JSONField(default=list, verbose_name='Vaqt boʻyicha dinamika')),
                ('drivers', models.JSONField(default=list, verbose_name='Asosiy omillar')),
                ('recommendations', models.JSONField(default=list, verbose_name='Tavsiyalar')),
                ('satellite_sources', models.JSONField(default=list, verbose_name='Sunʼiy yoʻldosh manbalari')),
                ('source', models.CharField(choices=[('ai', 'AI (OpenRouter)'), ('engine', 'Ichki model')], default='engine', max_length=10, verbose_name='Manba')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='risk.region', verbose_name='Hudud')),
            ],
            options={
                'verbose_name': 'Prognoz',
                'verbose_name_plural': 'Prognozlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='risk.prediction')),
            ],
            options={
                'verbose_name': 'AI suhbat xabari',
                'verbose_name_plural': 'AI suhbat xabarlari',
                'ordering': ['created_at'],
            },
        ),
    ]
