# Generated by Django 5.1.15 on 2026-10-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_prediction_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='language',
            field=models.CharField(db_index=True, default='uz', max_length=5),
        ),
    ]
