"""Write the Android app's string table (Kotlin) from the website's translation catalogs."""
import re

from django.core.management.base import BaseCommand

from risk.locale_mobile import APP
from risk.locale_ui import UI

LANGS = ("uz", "en", "ru", "kaa")


def kt(text):
    text = re.sub(r"<[^>]+>", "", text)  # app shows plain text (web *_html keys contain spans)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\$").replace("\n", "\n") + '"'


class Command(BaseCommand):
    help = "Export UI + app strings to a Kotlin file for the Android app."

    def add_arguments(self, parser):
        parser.add_argument("path")

    def handle(self, path, **opts):
        table = {**UI, **APP}
        lines = [
            "// GENERATED by `python manage.py export_mobile_strings` from risk/locale_ui.py + risk/locale_mobile.py.",
            "// Do not edit by hand — change the catalogs on the website and re-export.",
            "package uz.spacerisk.app.i18n",
            "",
            "@Suppress(\"LargeClass\")",
            "internal object Catalog {",
        ]
        for lang in LANGS:
            lines.append(f"    val {lang}: Map<String, String> = mapOf(")
            for key in sorted(table):
                lines.append(f"        {kt(key)} to {kt(table[key][lang])},")
            lines.append("    )")
        lines.append("}")
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("\n".join(lines) + "\n")
        self.stdout.write(self.style.SUCCESS(f"{len(table)} keys × {len(LANGS)} languages → {path}"))
